### ISSUE TITLE
Discuss whether to submit Autogenerated files or not to submit them, as part of  git commit

### ISSUE THREAD

**Issue by yogeshbdeshpande** [veraison/services#10]
Discuss whether to submit Autogenerated files or not to submit them, as part of  git commit ?

Evaluate the pros and cons and come to a conclusion

**Comment by yogeshbdeshpande** [comment]
@setrofim Agree with your suggestion to track Autogenerated files using a separate PR linking to this issue.
We discuss and close/merge the PR and the issue, based on what we decide!

**Comment by setrofim** [comment]
As per face-to-face discussion, due to https://github.com/veraison/services/issues/19, the decision is to have the generated files in the repo, in order to make it easier for outsider user of the services module. 

https://github.com/veraison/services/pull/21 re-introduces the files.
