### ISSUE TITLE
BUG: Unrecognised instance and implementation id in claims template causes silent failure

### ISSUE THREAD

**Issue by SabreenKaur** [veraison/services#107]
When using an unrecognised psa-instance-id or psa-implementation-id in the claims template that is used to generate the evidence used during verification, the application fails silently. There is no detail on the failure outputted in logging or any attestation result outputted. The application exits with a `status: failed `in the response body, when testing this using the Tavern testing framework.

The failure happens inside the `getrustAnchor(id string)` function in `services/vts/trustedservices_grpc.go`. The  error happens when `TaStore.Get(id)` is called. An example of the error given when manually printed is the following:

```
key not found: "PSA_iot://0/YWNtZS1pbXBsZW1lbnRhdGlvbi1pZC0wMDAwMDAwMDE=/Aaq7zN0AESIzqrvM3QARIjOqu8zdABEiM6q7zN0AESIz
```
Where `Aaq7zN0AESIzqrvM3QARIjOqu8zdABEiM6q7zN0AESIz` is the invalid instance id used in the template that is used to synthesise the evidence.

We expect to see the attestation result successfully output with the trust vector populated. For example, for an unrecognised instance identity or implementation id the trust vector entry for the instance identity should be: `instance-identity:97`

**Comment by setrofim** [comment]
Addressed by https://github.com/veraison/services/pull/135
