### ISSUE TITLE
BUG: Invalid signed evidence causes silent verification error

### ISSUE THREAD

**Issue by SabreenKaur** [veraison/services#114]
When using a fully valid template with invalid sinage, there is a silent verification error and the application exits with `status: failed` in the response body.

This failure happens when `scheme.ValidateEvidenceIntegrity(token, ta, endorsements)` is called in `services/vts/trustedservices_grpc.go`. The error printed when manually logged is the following:

```
verification error
```

We expect to see the attestation result successfully output with the trust vector populated. For example, for an invalid signage, all entries in the trust vector should be populated with 99s.

**Comment by setrofim** [comment]
Addressed by https://github.com/veraison/services/pull/135
