### ISSUE TITLE
Policy Management framework.

### ISSUE THREAD

**Issue by setrofim** [veraison/services#16]
We need to figure out how policies are managed. Specifically:

- Which entity(ies) is responsible for establishing attestation policies?
- At what points can these policies be added/amended/deleted? 
- Are there auditing requirements (e.g. do we want to keep "deleted" policies in case they need to be reviewed at a future point?
- Is it possible for multiple policies to be applicable to a single evaluation, and if so, how/in what order should they be applied?

**Comment by yogeshbdeshpande** [comment]
Should we also mention, how policies can be added into an Attestation Verification System?

1) Through Supply Chain by the Verification owner?
OR
2) Through configuration which is set by the Verification Owner as part of Deployment?

**Comment by yogeshbdeshpande** [comment]
@setrofim : I understand this issue is now resolved ? Can you please check and close the issue!
