### ISSUE TITLE
Policy support in the `AttestationResult`

### ISSUE THREAD

**Issue by setrofim** [veraison/services#17]
Current policy implementation if fairly limited -- it allows overwriting the result status and the trust vector values. We may want to give the policy the ability to add new derived claims, and also make the changes made by policy more transparent. In order to do that, we need to consider how this ought to be handled in the `AttestationResult` (if at all).

- Where in `AttestationResult` should the policy-derived claims reside? In its current implementation, the post appropriate place seems to be under "endorsed claims" but that doesn't seem quite right --  logically, there is a difference between claims directly provisioned/endorsed by an outside entity, and those generated based on policy.
- What is the right way to keep track of changes made by policy, and to they need to be exposed to the Relying Party inside the `AttestationResult` (if so, where)? The alternative would be to log them, either via generic application logging, or through some dedicated mechanism.

**Comment by thomas-fossati** [comment]
> What is the right way to keep track of changes made by policy, and to they need to be exposed to the Relying Party inside the AttestationResult (if so, where)? The alternative would be to log them, either via generic application logging, or through some dedicated mechanism.

we could store a trace of the execution and make it available via a stable URL. (And stash the URL -- or an equivalent URI that can be resolved in some way -- inside the attestation result.)

**Comment by yogeshbdeshpande** [comment]
Policy Claims can now be added in AttestationResults. Please refer to `services/vts/appraisal.go`  `AddPolicyClaim`
