### ISSUE TITLE
BUG: `proto` module does not have `*.go` files checked in

### ISSUE THREAD

**Issue by dreemkiller** [veraison/services#19]
### What version of the package are you using?
dc401170e1c974b2cd38373f5712cf2bc979fd55

### Does this issue reproduce with the latest release?
Yes

### What OS and CPU architecture are you using (`go env`)?
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ec2-user/.cache/go-build"
GOENV="/home/ec2-user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ec2-user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ec2-user/go/"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/ec2-user/services/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build24166057=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
Tried to use `services` and it's submodules outside of the `services` directory (as a go dependency)

### What did you expect to see?
I expected to be able to build my project

### What did you see instead?
```
../pure/services/vts/pluginmanager/ipluginmanager.go:6:2: no required module provides package github.com/veraison/services/proto; to add it:
	go get github.com/veraison/services/proto
```
Running `go get ...` results in:
```
go: module github.com/veraison/services@upgrade found (v0.0.0-20220823172721-dc401170e1c9,), but does not contain package github.com/veraison/services/proto
```
This is happening because none of the `*.go` files generated by `protoc` are checked into the directory. This means that in order to use any of the modules that depend on the `proto` module, the user needs to download the project (via `git clone ...`), install the `protoc` compiler, and run `make`. If the files where checked in, this would not be necessary.

**Comment by setrofim** [comment]
This has been resolved by https://github.com/veraison/services/pull/21
