### ISSUE TITLE
TLS FTW!

### ISSUE THREAD

**Issue by thomas-fossati** [veraison/services#191]
Authentication and integrity of the transport channels between clients and Veraison services, as well as between services, are prerequisite for the overall system security.  Encryption may also be a requisite in some (most) cases.

Currently:
* all Veraison REST APIs run over plain-text HTTP
* intra-service gRPC traffic is over plain TCP
* communication to extra services (e.g., KeyCloak) is over HTTP

We should ensure all traffic above is carried over secure (authenticated and encrypted) channels.

**Comment by thomas-fossati** [comment]
> @thomas-fossati I would prefer acronym expansion in the title of the work

this is not an acronym, it's slang 😄

**Comment by yogeshbdeshpande** [comment]
> > @thomas-fossati I would prefer acronym expansion in the title of the work
> 
> this is not an acronym, it's slang 😄

Then I would certainly change it!

**Comment by setrofim** [comment]
It is both -- the acronym stands for "For The Win", which is a well-known net expression. And as a counter-point  I would leave it in :D -- it brings the point across nicely.

**Comment by yogeshbdeshpande** [comment]
@setrofim It is not completely true. Google search reveals other terms also, not worth mentioning it here !

**Comment by setrofim** [comment]
Sure, pretty much any TLA will have multiple decodings (a lot of which will not be worth mentioning). However, outside of specific contexts, FTW is broadly and unambiguously undestood to mean "For The Win".  (Just like "IIRC" can decode as "International Integrated Reporting Council" or "If I Really Cared", but is broadly understood to mean "If I Understand Correctly" in general).

**Comment by thomas-fossati** [comment]
> @setrofim It is not completely true. Google search reveals other terms also, not worth mentioning it here !

LOL, the context is everything :-)

**Comment by thomas-fossati** [comment]
The scope of this issue is wider than just the external API.  It includes:

* [x] all Veraison REST APIs run over plain-text HTTP
* [ ] intra-service gRPC traffic is over plain TCP
* [ ] communication to extra services (e.g., KeyCloak) is over HTTP

#229 addresses the first of the three points.

Alternatively, we could move the remaining two to new issues and mark this closed.

**Comment by setrofim** [comment]
Resolved by https://github.com/veraison/services/pull/234
