### ISSUE TITLE
BUG: Need to have a Harmonised view of IAK Public Key 

### ISSUE THREAD

**Issue by yogeshbdeshpande** [veraison/services#20]
Current Veraison Provisioning requirement is:
To have a IAK Key encoded in CoMID as:
 The IAK public key is a PEM-encoded as SubjectPublicKeyInfo [RFC5280]

However in the Verifier code base, we need a proper PEM Key with PEM Header:
"--BEGNI PUBLIC KEY---" 

So we need to check:

Agree on a consistent format between the Provisioning and the Verification Entity

Ensure that whatever Veraison format is : "User Friendly for Community members"
1) Users can generate the Public Keys easily.

2) Users are able to introduce the keys easily in the CoMID for provisioning.

3) Users can easily access the Private Key to sign the Attestation token containing the Evidence Claims

**Comment by setrofim** [comment]
This has been resolved by https://github.com/veraison/services/commit/f26d1b17ba65e6bb1d5130d50fa9ecc6844766cc
