### ISSUE TITLE
BUG: generated files in `verification/api/mocks` are not checked in

### ISSUE THREAD

**Issue by dreemkiller** [veraison/services#24]
### What version of the package are you using?
latest

### Does this issue reproduce with the latest release?
yes

### What OS and CPU architecture are you using (`go env`)?
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ec2-user/.cache/go-build"
GOENV="/home/ec2-user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ec2-user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ec2-user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/ec2-user/VeracruzVerifier/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4222535396=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
Attempted to use `services` from an out-of-branch project

### What did you expect to see?
Expected to be able to build my project and use the Veraison modules

### What did you see instead?

```
go: finding module for package github.com/veraison/services/provisioning/api/mocks
github.com/veraison/services/provisioning/api tested by
	github.com/veraison/services/provisioning/api.test imports
	github.com/veraison/services/provisioning/api/mocks: no matching versions for query "latest"
github.com/veraison/services/verification/api tested by
	github.com/veraison/services/verification/api.test imports
	github.com/veraison/services/verification/api/mocks: no matching versions for query "latest"
```

It seems that the `mocks` directory and it's contents are generated when running `make`. However, when working outside of the `services` tree, I cannot do, that. So it seems that this would be possible if those generated files were checked into git.

**Comment by setrofim** [comment]
Please could you provide the go command you're running that  results in the above error?

**Comment by thomas-fossati** [comment]
hi @dreemkiller, this should only pop-up if the `test` target is invoked.  Is there a reason why you need to have it as part of your build?

**Comment by thomas-fossati** [comment]
> Please could you provide the go command you're running that results in the above error?

Yes, if you could provide an environment where we can reproduce this it'd be great.

**Comment by setrofim** [comment]
We were able to reproduce the issue. Now looking into the solution.
