### ISSUE TITLE
BUG: vts policymanager getPolicy will never return ErrNoPolicy

### ISSUE THREAD

**Issue by dreemkiller** [veraison/services#25]
### What version of the package are you using?
aa55d1502134308f1f3d66399ca5a8bd378b47c2

### Does this issue reproduce with the latest release?
Yes (that's latest)

### What OS and CPU architecture are you using (`go env`)?
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ec2-user/.cache/go-build"
GOENV="/home/ec2-user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ec2-user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ec2-user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/ec2-user/VeracruzVerifier/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3596495490=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

It's complicated, since I'm calling it from Veracruz. I'm using the kvstore/Memory backend.

### What did you expect to see?
`getPolicy` should return `ErrNoPolicy` when there is no policy loaded

### What did you see instead?
`getPolicy` returns the error generated by `o.Store.Get`, which is not `ErrNoPolicy`
The error generated is from `kvstore/memory.go`, line 49 in my version, of the format:
```
return nil, fmt.Errorf("key %q not found", key)
```
Since `getPolicy` returns the wrong error message, the check:
```
if err == ErrNoPolicy
```
that is used to make sure we handle the no policy case elegantly does not match.

**Comment by dreemkiller** [comment]
A potential fix is presented in #26

**Comment by setrofim** [comment]
This has been addressed by https://github.com/veraison/services/pull/30

**Comment by dreemkiller** [comment]
Does not appear to be fixed. `getPolicy` will now return  `fmt.Errorf("%w: %q", ErrNoPolicy, policyID)`. When `getPolicy` is called in `Evaluate`, it's return value is tested as:
https://github.com/veraison/services/blob/341d1a834b831ec03bbe8c270adf4f1d39df3dfe/vts/policymanager/policymanager.go#L43

Since the returned error is not exactly `ErrNoPolicy`, this will never be true.

It appears that changing the test to:
```
if errors.Is(err, ErrNoPolicy) {
```
does work, however.

**Comment by setrofim** [comment]
(Re-)resolved by https://github.com/veraison/services/pull/38
