### ISSUE TITLE
feature: Ability to add additional provisioning and verification plugins without modifying the `services` project

### ISSUE THREAD

**Issue by dreemkiller** [veraison/services#28]
### Is your feature request related to a problem? Please describe

I am working to add attestation plugins for AWS Nitro enclaves (mostly for my own edification, but possibly to upstream). In general, things work well. However, I have had to make one change to existing code in the `services` project to enable this. It's in `proto/attestation_format.proto`, where I had to add an additional entry in the `AttestationFormat` enum, `AWS_NITRO = 4;`. Of course this change meant that the generated files needed to be changed as well, but this is the only manual change that was required.

I would be beneficial to not have to make this change, because besides this change, nothing else in any existing code needed to be modified. This would allow people to develop plugins outside of the `services` project without having to fork the project.

### If possible, describe a solution

I'm not sure what the best solution here would be. One possible (though awkward) solution would be to make `AttestationFormat` a string instead of an enum. Then plugins and the infrastructure code could match against strings.

## Additional context

This work is in connection to the Veracruz project's use of Veraison `services`.

**Comment by thomas-fossati** [comment]
This is something that regularly comes up in our discussion.  I guess one advantage of requiring the attestation scheme to be registered in the proto file is that it works effectively as a single registration point, which avoids clashes.

**Comment by dreemkiller** [comment]
Also, as currently written, the developer of the plugin needs to modify a `.proto` file, requiring them to have the exact same version of `protoc` that the project uses, otherwise the diff on the PR blows up (also, presumably the project wants to maintain adherence to a specific `protoc` binary version). If the file that needed to be modified was a `.go` file, this step would not be necessary and `protoc` would not even need to be installed on their system.

**Comment by yogeshbdeshpande** [comment]
@dreemkiller : The issue has been addressed now, with the introduction of plugin discovery and returned `media-types` from individual plugin implementations.
