### ISSUE TITLE
corim-psa-decoder is base64 encoding data that is already base64 encoded

### ISSUE THREAD

**Issue by dreemkiller** [veraison/services#3]
In the file `provisioning/plugins/corim-psa-decoder/classattributes.go`, line 36 (in my version) looks lke:
```
o.ImplID, _ = implID.MarshalJSON()
```
However, the implID is already base64 encoded, and the MarhsalJSON() method base64 encodes it again.
In my code (not able to do a PR because my tree has all sorts of fun in it), changing it to:
```
o.ImplID = implID[:]
```
works and gives me the expected results.

**Comment by yogeshbdeshpande** [comment]
This has been already fixed, in the incoming PR.
