### ISSUE TITLE
BUG: Missing mocks under services/vts/policymanager

### ISSUE THREAD

**Issue by yogeshbdeshpande** [veraison/services#32]
Mocks under services/vts/policymanager needs to be submitted for command `go mod tidy` to execute correctly.

Issue linked to #24

**Comment by thomas-fossati** [comment]
I think this should be looked at in the context of #16

**Comment by yogeshbdeshpande** [comment]
I think, this code establishes the policy management framework, so we can include the same. Issue #16 add meat to the framework? We just need enough unit tests to cover the framework?
