### ISSUE TITLE
feature: each service should have a versioned "is running" route

### ISSUE THREAD

**Issue by dreemkiller** [veraison/services#46]
### Is your feature request related to a problem? Please describe

When starting a Veraison-based service as part of my test suite, I find I need to add `sleep` commands to wait for the service to be up. The amount of time required for this varies by platform, and has caused intermittent failures.

In specific, this problem is about the Provisioning service, but it's a general problem with all services.

In addition, in preparation for the support of multiple service versions, we have no simple way to detect which versions are supported by a service.

### If possible, describe a solution

If each service were to support a simple versioned `GET` path (for provisioning service, it might be to `/endorsement-provisioning/v1`), this could solve both problems. If a `GET` on a specific version returned non-success (`404`, I suppose), the caller would know that version was not supported by the service. If it returned "connection refused" the caller would know that the service wasn't up on that URL/port.

### Describe alternatives you have considered

We've attempted `sleep`, as mentioned above, but this adds unnecessary delays in our test suite and has shown intermittent failures on most platforms due to variable loads. The versioning question is also not solved with that solution.

**Comment by thomas-fossati** [comment]
Thanks for raising this, it looks like a useful feature.

We could either:

* Support [`HEAD`](https://www.rfc-editor.org/rfc/rfc9110.html#section-9.3.2) on the existing API paths.
* Expose a [`.well-known`](https://www.rfc-editor.org/rfc/rfc8615) with metadata about the service(s) including high-level status indication that could be queried.

**Comment by setrofim** [comment]
Implemented by https://github.com/veraison/services/pull/50
