### ISSUE TITLE
services build-time information

### ISSUE THREAD

**Issue by thomas-fossati** [veraison/services#51]
We should make build-time information, including but not limited to version, available to all executables, both services and CLIs.

Re: version. One option would be for it to be computed at build time from git metadata (e.g., tags, commit hash, etc.) and assigned to a predefined global via `go build -w -X VERSION_VAR=VERSION_VAL` made available to all binaries.

**Comment by setrofim** [comment]
Implemented by #50 and #55

**Comment by thomas-fossati** [comment]
I think we should also have versioning in the two API frontend services.
