### ISSUE TITLE
Feature: Integrate Arango Instance into kvstore backend

### ISSUE THREAD

**Issue by yogeshbdeshpande** [veraison/services#62]
Enhance kvstore to have a DB instance of ArangoDB.

Present work will integrate Arango as a Document DB, i.e. a Key/Val Store.

Issue moved here from: https://github.com/veraison/veraison/issues/141
As part of Veraison/veraison migration to veraison/services

**Comment by setrofim** [comment]
Do we still need this? `kvstore` exposes very simple functionality, and advanced features of ArangoDB would be wasted. It is not clear that for our use case ArongoDB has any advantage over alternatives such ad MongoDB, DynamoDB, or appropriately configured relational DB. 

We should probably not have a requirement to implement a specific backend until we know there is actual demand for it.
