### ISSUE TITLE
feature:  Capability Discovery API

### ISSUE THREAD

**Issue by yogeshbdeshpande** [veraison/services#80]
### Is your feature request related to a problem? Please describe

A Relying Party is assumed to have implicit knowledge of the capabilities of a Verifier e.g. what tokens are supported and what constraints are applied to that token support e.g. the supported signature algms.

### If possible, describe a solution

Add a discovery API that would describe the configured tokens for this deployment. Schema is TBD but probably related to the configuration of the Verifier. 

Advanced uses: links to peer deployments, potentially with different tokens supported; conveyance of additional trust data for the RP to evaluate.

### Describe alternatives you have considered

Alternative: a probe-and-fail pattern for an agreed template form of a stub token submitted to the Verification API.

## Additional context

NA

**Comment by thomas-fossati** [comment]
We need to add a [`.well-known` URIs](https://en.wikipedia.org/wiki/Well-known_URI) to the exposed APIs (verification and provisioning for now) that provide meta information about the Veraison deployment.

At least, we need to present:
* the exposed API entry-points
* the verification keys for the produced EARs (that can be used as `kid` in EARs themselves)
* the supported evidence media types
* the supported endorsements media types

Tasks:
* [ ] design the info model
* [ ] document the API under [veraison/docs/api](https://github.com/veraison/docs/tree/main/api)
* [ ] extend the API frontends

Background reading:
* [ACME "Directory" object](https://www.rfc-editor.org/rfc/rfc8555.html#section-7.1.1)
* [OpenID Connect well-known URL](https://help.akana.com/content/current/cm/api_oauth/oauth_discovery/m_oauth_getOpenIdConnectWellknownConfiguration.htm)
* [IANA well-known URI registry](https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml)
