### ISSUE TITLE
integration testing

### ISSUE THREAD

**Issue by thomas-fossati** [veraison/services#84]
Now that we have #41 we can move to _"define the SUT for a subsequent "integration testing" story."_

As devs, we want to have an integration test environment where a number of representative tests  -- both at component-level and end-to-end -- can be run using different, well-defined fixtures.

A bunch of desiderata follows:

* [x] A dev should be able to run individual integration tests on the command line
* [x] Each test should report its exit status
* [x] Each test should collect and make available the execution logs for each of the components as well as the test
* [x] A dev should be able to run all tests using a simple `make integration-tests` target
* [ ] Ideally, integration tests would be part of the existing Golang test suite
* [x] These tests should be run as part of the GitHub CI (either nightly or on push depending on their "cost")

**Comment by SabreenKaur** [comment]
- [ ] One negative test
- [ ] Documentation on how to write integration tests
