### ISSUE TITLE
feature: need a build environment available in a Docker container

### ISSUE THREAD

**Issue by yogeshbdeshpande** [veraison/services#88]
@dreemkiller : I have migrated your issue here as the veraison/veraison will soon be deprecated!
### Is your feature request related to a problem? Please describe

The instructions in the `BUILD.md` file presume the user has a properly configured environment set up. While setting up this environment is fairly easy, if the user moves to a new system, the set up needs to be done again.

### If possible, describe a solution

I have implemented one for myself here: https://github.com/dreemkiller/veraison_docker

Basically, it has a Dockerfile that sets up the environment, and a Makefile that builds the docker container, runs it while attaching the `veraison` directory to it, and allows the user to start a shell in the running container.

### Describe alternatives you have considered

Another possibility is to provide instructions on how to set up the environment. However, these steps would need to be done for every platform the user needed to build on. The industry seems to be trending towards docker for these cases instead.

## Additional context

I've found it helpful to not rely on prebuilt docker images that contain the golang toolset, as if you need to integrate your

**Comment by yogeshbdeshpande** [comment]
@dreemkiller Wrote:
Note that the above docker image is aarch64-specific. Some (small?) amount of work would need to be done to make it arch independent.

**Comment by dreemkiller** [comment]
The specific problem: I need a portable development environment, because Veracruz supports multiple different platforms and my development work moves around depending upon a lot of different things. Being able to take the environment with me (via a Docker file) is preferable to setting up the entire environment every time I move to a new platform.

**Comment by thomas-fossati** [comment]
I think this has been addressed by #84, and further refined by #125.

Feel free to reopen if this is not the case.
