### ISSUE TITLE
`ExtractVerifiedClaims` in `scheme-psa-iot` appears to be expecting the wrong format

### ISSUE THREAD

**Issue by dreemkiller** [veraison/services#9]
When I look at the `ExtractVerifiedClaims` function in the `scheme-psa-iot` plugin for `vts`, I see that the code is expecting `trustAnchor` to be PEM encoded. 

However, when I execute the code, I find that the `trustAnchor` input is JSON data instead. This meant that I had to essentially rewrite the function for the different data format.

Is it possible that I am using the plugin wrong (I am not aware of any changes that I've made to that part of the code)? Or is this a bug?

**Comment by yogeshbdeshpande** [comment]
The Verification format for PSA is now aligned with the Provisioning format. Please see the PR https://github.com/veraison/services/pull/4

**Comment by yogeshbdeshpande** [comment]
This has now been addressed!
