### ISSUE TITLE
feature: Evaluate & introduce if a new scheme is required for CCA

### ISSUE THREAD

**Issue by yogeshbdeshpande** [veraison/services#90]
Need to check whether CCA Needs a new Scheme ?

If required, this issue tracks introducing one!

**Comment by setrofim** [comment]
Is this a duplicate of https://github.com/veraison/services/issues/54 and https://github.com/veraison/services/issues/53?

**Comment by yogeshbdeshpande** [comment]
The changes for introducing new scheme will be handled vi #54 

Closing this issue.
